name: docker_bidmc
- pip:
  - gin-config==0.2.1
  - matplotlib==3.1.2
  - nilearn==0.6.0
  - nipype==1.3.1
  - Pillow==6.2.1
  - pydicom==1.3.0
  - pynetdicom==1.4.1
  - pyodbc==4.0.27
  - SQLAlchemy==1.3.11